# Generated by Django 4.0.4 on 2022-11-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_testcourse_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_id',
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='hyperlink',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='num_credits',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='restrictions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
