# Generated by Django 4.0.4 on 2022-11-06 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_prerequisite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequisite',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prereq_course_id', to='api.course'),
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depend_course_id', to='api.course')),
                ('course_id_depend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_id_depend', to='api.course')),
            ],
        ),
    ]
