# Generated by Django 4.0.4 on 2023-06-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dependency_api_depende_course__02b924_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTable2023',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('restrictions', models.TextField(null=True)),
                ('hyperlink', models.CharField(max_length=255, null=True)),
                ('num_credits', models.IntegerField(null=True)),
                ('raw_preq', models.TextField(null=True)),
                ('clean_preq', models.TextField(null=True)),
                ('marked_preq', models.TextField(null=True)),
                ('dependent_courses', models.TextField(null=True)),
                ('not_in_catalogue', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='dependency',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='dependency',
            name='course_id_depend',
        ),
        migrations.RemoveField(
            model_name='prerequisite',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='prerequisite',
            name='course_id_prereq',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Dependency',
        ),
        migrations.DeleteModel(
            name='Prerequisite',
        ),
    ]
