# Generated by Django 4.0.4 on 2023-06-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_coursetable2023_remove_dependency_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetable2023',
            name='not_in_catalogue',
            field=models.BooleanField(),
        ),
    ]
